/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Poll } from "./Poll";
export * as factories from "./factories";
export { Poll__factory } from "./factories/Poll__factory";
