/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TriviaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addQuestion"
      | "answerQuestion"
      | "getQuestionCount"
      | "hasAnswered"
      | "owner"
      | "questions"
      | "rewardToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CorrectAnswer" | "QuestionAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addQuestion",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "answerQuestion",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuestionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasAnswered",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "questions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "answerQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuestionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAnswered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "questions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
}

export namespace CorrectAnswerEvent {
  export type InputTuple = [
    questionId: BigNumberish,
    player: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    questionId: bigint,
    player: string,
    reward: bigint
  ];
  export interface OutputObject {
    questionId: bigint;
    player: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestionAddedEvent {
  export type InputTuple = [questionId: BigNumberish, reward: BigNumberish];
  export type OutputTuple = [questionId: bigint, reward: bigint];
  export interface OutputObject {
    questionId: bigint;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Trivia extends BaseContract {
  connect(runner?: ContractRunner | null): Trivia;
  waitForDeployment(): Promise<this>;

  interface: TriviaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addQuestion: TypedContractMethod<
    [_question: string, _answer: string, _reward: BigNumberish],
    [void],
    "nonpayable"
  >;

  answerQuestion: TypedContractMethod<
    [_questionId: BigNumberish, _answer: string],
    [void],
    "nonpayable"
  >;

  getQuestionCount: TypedContractMethod<[], [bigint], "view">;

  hasAnswered: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  questions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        question: string;
        answerHash: string;
        reward: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  rewardToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addQuestion"
  ): TypedContractMethod<
    [_question: string, _answer: string, _reward: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "answerQuestion"
  ): TypedContractMethod<
    [_questionId: BigNumberish, _answer: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getQuestionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasAnswered"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "questions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        question: string;
        answerHash: string;
        reward: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CorrectAnswer"
  ): TypedContractEvent<
    CorrectAnswerEvent.InputTuple,
    CorrectAnswerEvent.OutputTuple,
    CorrectAnswerEvent.OutputObject
  >;
  getEvent(
    key: "QuestionAdded"
  ): TypedContractEvent<
    QuestionAddedEvent.InputTuple,
    QuestionAddedEvent.OutputTuple,
    QuestionAddedEvent.OutputObject
  >;

  filters: {
    "CorrectAnswer(uint256,address,uint256)": TypedContractEvent<
      CorrectAnswerEvent.InputTuple,
      CorrectAnswerEvent.OutputTuple,
      CorrectAnswerEvent.OutputObject
    >;
    CorrectAnswer: TypedContractEvent<
      CorrectAnswerEvent.InputTuple,
      CorrectAnswerEvent.OutputTuple,
      CorrectAnswerEvent.OutputObject
    >;

    "QuestionAdded(uint256,uint256)": TypedContractEvent<
      QuestionAddedEvent.InputTuple,
      QuestionAddedEvent.OutputTuple,
      QuestionAddedEvent.OutputObject
    >;
    QuestionAdded: TypedContractEvent<
      QuestionAddedEvent.InputTuple,
      QuestionAddedEvent.OutputTuple,
      QuestionAddedEvent.OutputObject
    >;
  };
}
